/* Populate tabla clientes */
INSERT INTO CV_VENDEDOR (CV_NUM_EMPLEADO, CV_NOMBRE, CV_APELLIDO, CV_FECHA_CREADO) VALUES ('202110001', 'Juan', 'Garnizo','2021-10-14');
INSERT INTO CV_VENDEDOR (CV_NUM_EMPLEADO, CV_NOMBRE, CV_APELLIDO, CV_FECHA_CREADO) VALUES ('202110002', 'Sergio', 'Esparza','2021-10-14');
INSERT INTO CV_VENDEDOR (CV_NUM_EMPLEADO, CV_NOMBRE, CV_APELLIDO, CV_FECHA_CREADO) VALUES ('202110003', 'Ron', 'Howard','2021-10-14');
INSERT INTO CV_VENDEDOR (CV_NUM_EMPLEADO, CV_NOMBRE, CV_APELLIDO, CV_FECHA_CREADO) VALUES ('202110004', 'Elizabeth', 'Olsen','2021-10-14');
INSERT INTO CV_VENDEDOR (CV_NUM_EMPLEADO, CV_NOMBRE, CV_APELLIDO, CV_FECHA_CREADO) VALUES ('202110005', 'John', 'Wick','2021-10-14');

-- Inserta Platillos
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Pizza a la Leña Chica', 30, 1, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Pizza a la Leña Mediana', 50, 1, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Rebanada de Pay de Limón', 30, 3, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Rebanada de Pastel de Chocolate', 30, 3, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Jugo de Naranja', 15, 2, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Pizza a la Leña Grande', 70, 1, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Rib Eye 800g', 100, 1, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Mezcal', 85, 2, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Tequila', 40, 2, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Rebanada de Pay de Queso', 30, 3, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Café Americano', 20, 2, '2021-10-14')
INSERT INTO CV_PLATILLO (CV_NOMBRE, CV_PRECIO, CV_CATEGORIA, CV_FECHA_CREADO) VALUES('Café Capuchino', 40, 2, '2021-10-14')